# Generated by Django 5.2.4 on 2025-07-24 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cachorro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_cachorro', models.CharField(max_length=200)),
                ('description_cachorro', models.TextField(blank=True)),
                ('adoptado', models.BooleanField(default=False)),
            ],
        ),
    ]
